---

- name: Post building phase
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    container_tool: "{{ lookup('env', 'DOCKER_BINARY') }}"
    docker_push: "{{ lookup('env', 'DOCKER_PUSH') | default(False) }}"
  tasks:

    - name: Save container to image (docker)
      when:
        - container_tool == 'docker'
        - build_vars.container.name is defined
      block:

        - name: Load pipeline variable from file
          ansible.builtin.set_fact:
            build_vars: "{{ lookup('file', 'docker-settings.yml') | from_yaml }}"

        - name: Get image info
          ansible.builtin.include_tasks:
            file: tasks/image-info.yml
          vars:
            image_name: "{{ build_vars.image.name }}:tmp"
            cmd: Cmd
            entrypoint: Entrypoint

        - name: Save running container as image
          ansible.builtin.command: >
            docker commit
            {{ build_vars.container.name }}
            {{ build_vars.image.name }}:tmp

        - name: Show Dockerfile for entrypoint restore
          ansible.builtin.debug:
            msg: |
              FROM {{ build_vars.image.name }}:tmp
              {% if Entrypoint | length > 0 %}
              ENTRYPOINT {{ Entrypoint | to_json }}
              {% else %}
              ENTRYPOINT []
              {% endif %}
              {% if Cmd | length > 0 %}
              CMD {{ Cmd | to_json }}
              {% endif %}

        - name: Create Dockerfile for entrypoint restore
          ansible.builtin.copy:
            content: |
              FROM {{ build_vars.image.name }}:tmp
              {% if Entrypoint | length > 0 %}
              ENTRYPOINT {{ Entrypoint | to_json }}
              {% else %}
              ENTRYPOINT []
              {% endif %}
              {% if Cmd | length > 0 %}
              CMD {{ Cmd | to_json }}
              {% endif %}
            dest: "{{ buildpath }}/Dockerfile.restore"
            mode: "0640"

        - name: Rebuild with original entrypoint and cmd
          community.docker.docker_image:
            name: "{{ build_vars.image.name }}:{{ build_vars.image.tag }}"
            source: build
            build:
              path: "{{ buildpath }}"
              dockerfile: Dockerfile.restore

        - name: Add additional tags
          ansible.builtin.command: >-
            docker image tag
            {{ build_vars.image.name }}:{{ build_vars.image.tag }}
            {{ build_vars.image.name }}:{{ item }}
          changed_when: true
          loop: "{{ build_vars.image.tags | default([]) }}"

        - name: Get image info
          ansible.builtin.include_tasks:
            file: tasks/image-info.yml
          vars:
            image_name: "{{ build_vars.image.name }}:{{ build_vars.image.tag }}"
            cmd: Cmd
            entrypoint: Entrypoint

        - name: Delete the intermediate image
          community.docker.docker_image:
            name: "{{ build_vars.image.name }}"
            tag: tmp
            state: absent

    - name: Save container to image (podman)
      when:
        - container_tool == 'podman'
        - build_vars.container.name is defined
      block:

        - name: Load pipeline variable from file
          ansible.builtin.set_fact:
            build_vars: "{{ lookup('file', 'docker-settings.yml') | from_yaml }}"

        - name: Get image info
          ansible.builtin.include_tasks:
            file: tasks/image-info.yml
          vars:
            image_name: "{{ build_vars.image.name }}:{{ build_vars.image.tag }}"
            cmd: Cmd
            entrypoint: Entrypoint

        - name: Save running container as image
          ansible.builtin.command: >-
            podman container commit
            {{ build_vars.container.name }}
            {{ build_vars.image.name }}:{{ build_vars.image.tag }}
          changed_when: true

        - name: Add additional tags
          ansible.builtin.command: >-
            podman image tag {{ build_vars.image.name }}:{{ build_vars.image.tag }} {{ build_vars.image.name }}:{{ item }}
          changed_when: true
          loop: "{{ build_vars.image.tags | default([]) }}"
