---

- name: README role
  hosts: localhost
  connection: local
  gather_facts: no
#  vars_files:
#    - "{{ working_dir }}/.cicd"
  vars:
    tmpdir: "{{ lookup('env', 'TMPDIR') }}"
    github_owner: de-it-krachten
    github_repo: "{{ r_name }}"
    readme_file: README.md
    md_template: README-collection.md.j2

  tasks:

    - name: Show vars
      ansible.builtin.debug:
        msg:
          tmpdir: "{{ tmpdir }}"
          working_dir: "{{ working_dir }}"

    - name: Load configuration files
      ansible.builtin.set_fact:
        cicd_vars: "{{ lookup('file', working_dir + '/.cicd') | from_yaml }}"
        cicd_vars_overwrite: "{{ lookup('file', working_dir + '/.cicd.overwrite') | from_yaml }}"

    - name: Merge dicts
      ansible.builtin.set_fact:
        cicd: "{{ cicd_vars | combine(cicd_vars_overwrite, recursive=True) }}"

    - name: Define some sub-keys as top-level
      ansible.builtin.set_fact:
        "{{ item }}": "{{ cicd[item] }}"
      when: cicd[item] is defined
      loop:
        - generic
        - dependencies
        - platforms
        - platforms_overwrite
        - galaxy
        - github
        - gitlab
        - molecule
        - ci_templates
        - tasklists

    - name: Create README.md from template '{{ md_template }}' 
      ansible.builtin.template:
        src: "{{ md_template }}"
        dest: "{{ working_dir }}/{{ readme_file }}"
        mode: "0644"
