---

- name: Load pipeline variable from file
  ansible.builtin.set_fact:
    build_vars: "{{ lookup('file', 'docker-settings.yml') | from_yaml }}"

- name: Show settings
  ansible.builtin.debug:
    msg: "{{ build_vars }}"

- name: Define images
  ansible.builtin.set_fact:
    parent_image_name: "{{ build_vars.image.parent }}"
    container_image_name: "{{ build_vars.image.name }}:{{ build_vars.image.tag }}"
    container_image_tmp1: "{{ build_vars.image.name }}:tmp1"
    container_image_tmp2: "{{ build_vars.image.name }}:tmp2"

- name: Create of image tags
  ansible.builtin.set_fact:
    build_tags: >-
      [
        {%- for registry in registries -%}
        {%- for tag in [build_vars.image.tag] + (build_vars.image.tags | default([])) -%}
        "{{ registry }}/{{ build_vars.image.name }}:{{ tag }}",
        {%- endfor -%}
        {%- endfor -%}
      ]
  vars:
    registries: "{{ build_vars.image.registries | default([build_vars.image.registry]) }}"
